# JWT config
jwt.secret=TopSecretKeyForJWTGenerationWhichIsLongEnough
# 3600000 = 1 hour
jwt.expirationMs=3600000

spring.datasource.url=jdbc:h2:file:./target/data/petclinixdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

admin.username=admin
admin.password=supersecret123
