spring.application.name=petclinix-backend

server.servlet.context-path=/api

admin.username=${ADMIN_USERNAME:}
admin.password=${ADMIN_PASSWORD:}

#debug=true
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
